blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/zanedma/configly/discussions
    about: For general questions and discussions, please use GitHub Discussions
